//
// Created by karla on 18. 10. 2019..
//

#ifndef STEEPEST_DESCENT_OPTIMIZATION_FUNCTION_H
#define STEEPEST_DESCENT_OPTIMIZATION_FUNCTION_H


class optimization_function {

};


#endif //STEEPEST_DESCENT_OPTIMIZATION_FUNCTION_H
